# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor # type: ignore
from google.protobuf import descriptor_pool as _descriptor_pool # type: ignore
from google.protobuf import symbol_database as _symbol_database # type: ignore
from google.protobuf.internal import builder as _builder # type: ignore
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\"7\n\x07\x43ommand\x12\x11\n\tImplantID\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\"W\n\x11\x43lientTaskRequest\x12\x11\n\tImplantID\x18\x01 \x01(\t\x12\r\n\x05JobID\x18\x02 \x01(\t\x12\x10\n\x08\x46unction\x18\x03 \x01(\t\x12\x0e\n\x06Inputs\x18\x04 \x01(\t\"F\n\x12\x43lientTaskResponse\x12\x11\n\tImplantID\x18\x01 \x01(\x05\x12\r\n\x05JobID\x18\x02 \x01(\x05\x12\x0e\n\x06Output\x18\x03 \x01(\t\"\'\n\x06Packet\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x43SRF\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=16
  _globals['_COMMAND']._serialized_end=71
  _globals['_CLIENTTASKREQUEST']._serialized_start=73
  _globals['_CLIENTTASKREQUEST']._serialized_end=160
  _globals['_CLIENTTASKRESPONSE']._serialized_start=162
  _globals['_CLIENTTASKRESPONSE']._serialized_end=232
  _globals['_PACKET']._serialized_start=234
  _globals['_PACKET']._serialized_end=273
# @@protoc_insertion_point(module_scope)
